<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DemandaMacronutrienteCulturaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('demanda_macronutriente_cultura')->insert([
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 155,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 95,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 95,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 75,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 2,
                'quantidade' => 85,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 0,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 155,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 115,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 115,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 95,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 3,
                'quantidade' => 105,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 3,
                'quantidade' => 75,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 75,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 75,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 0,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 75,
                'medida' => 'kg de K₂O/ha',
            ],


             [
                'cultura_id' => 1,
                'cultivo' => 1,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 1,
                'cultivo' => 2,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 200,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 140,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 140,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 120,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 2,
                'quantidade' => 130,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 2,
                'quantidade' => 90,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 90,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 90,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 0,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 90,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 140,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 100,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 100,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 80,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 3,
                'quantidade' => 90,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 3,
                'quantidade' => 60,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 60,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 60,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 0,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 2,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 60,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 155,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 95,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 95,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 2,
                'quantidade' => 75,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 2,
                'quantidade' => 85,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 0,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 2,
                'quantidade' => 45,
                'medida' => 'kg de P₂O₅/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 110,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 70,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 70,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'BAIXO',
                'macronutriente_id' => 3,
                'quantidade' => 50,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 3,
                'quantidade' => 60,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'MÉDIO',
                'macronutriente_id' => 3,
                'quantidade' => 30,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 30,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 30,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 1,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 0,
                'medida' => 'kg de K₂O/ha',
            ],
            [
                'cultura_id' => 3,
                'cultivo' => 2,
                'teor_macronutriente' => 'MUITO ALTO',
                'macronutriente_id' => 3,
                'quantidade' => 30,
                'medida' => 'kg de K₂O/ha',
            ],
        ]);
    }
}
